# .travis.yml
language: node_js
dist: bionic
sudo: false

cache: npm

node_js:
  - '10'
  - '12'
  - '14'

notifications:
  email: false

env:
  - KNEX_TEST_TIMEOUT=60000

matrix:
  fast_finish: true
